NDefines.NMilitary.MAX_ARMY_EXPERIENCE = 800
NDefines.NMilitary.MAX_NAVY_EXPERIENCE = 800
NDefines.NMilitary.MAX_AIR_EXPERIENCE = 800
NDefines.NCountry.MIN_MAJOR_COUNTRIES = 10
NDefines.NCountry.ADDITIONAL_MAJOR_COUNTRIES_IC_RATIO = 0.9
NDefines.NRailwayGun.RAILWAY_GUN_POSSIBLE_RANGES = { 30, 15, 45, 125 }